import type { Metadata } from 'next';
import { LegalPage } from '@/components/LegalPage';
import { CONTACT_EMAIL, PERSONA_NAME, PRODUCT_NAME } from '@/lib/persona';

const UPDATED_AT = '2026-09-12';

export const metadata: Metadata = {
  title: `Privacy — ${PRODUCT_NAME}`,
  description: `What ${PRODUCT_NAME} stores, why, and how to have it deleted.`,
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy notice" updatedAt={UPDATED_AT}>
      <p>
        {PRODUCT_NAME} is a chat surface where you talk to an AI that answers as{' '}
        {PERSONA_NAME}. This page says what it keeps and who else sees it. It is written
        to be read, not to be survived.
      </p>

      <h2>What is stored</h2>
      <ul>
        <li>
          <strong>Your messages and the replies.</strong> The text of both, with the time
          each was sent. This is what makes a conversation continue instead of restarting
          every turn.
        </li>
        <li>
          <strong>An account, if you sign in with Google.</strong> Your name, email
          address, profile picture and the account identifier Google gives us. No password
          ever reaches this site.
        </li>
        <li>
          <strong>A browser identifier, if you do not.</strong> A random id kept in your
          browser so an anonymous conversation survives a refresh. It is not linked to
          anything else.
        </li>
      </ul>
      <p>
        Recorded audio is not kept. A spoken turn is transcribed and only the resulting
        text is stored, exactly as if you had typed it.
      </p>

      <h2>Who else sees it</h2>
      <ul>
        <li>
          <strong>The model provider.</strong> Replies are generated by a third-party
          large language model, so your message and the recent conversation are sent there
          to produce each answer.
        </li>
        <li>
          <strong>The speech service.</strong> A spoken turn is sent to a speech service
          that transcribes it and reads the reply back.
        </li>
      </ul>
      <p>
        Nothing is sold, and nothing is used for advertising or shared with anyone beyond
        what is needed to answer you.
      </p>

      <h2>How long</h2>
      <p>
        Conversations are kept until you ask for them to be deleted. A sign-in lasts 30
        days on a given browser, after which you sign in again.
      </p>

      <h2>Deleting it</h2>
      <p>
        Write to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> from the address
        you signed in with, and your account and every conversation attached to it will be
        removed. There is no self-service delete button yet; that is a gap, not a policy.
      </p>

      <h2>Changes</h2>
      <p>
        If what this page says changes in a way that matters, you will be asked to read it
        again before your next conversation.
      </p>
    </LegalPage>
  );
}
