import type { Metadata } from 'next';
import { LegalPage } from '@/components/LegalPage';
import { CONTACT_EMAIL, PRODUCT_NAME } from '@/lib/product';

const UPDATED_AT = '2026-09-14';

export const metadata: Metadata = {
  title: 'Privacy',
  description: `What ${PRODUCT_NAME} stores, why, and how to have it deleted.`,
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy notice" updatedAt={UPDATED_AT}>
      <p>
        {PRODUCT_NAME} hosts AI avatars of real people: you can talk to one, or launch one
        of yourself. This page says what it keeps and who else sees it. It is written to
        be read, not to be survived.
      </p>

      <h2>What is stored when you talk to an avatar</h2>
      <ul>
        <li>
          <strong>Your messages and the replies.</strong> The text of both, with the time
          each was sent and which avatar it was with. This is what makes a conversation
          continue instead of restarting every turn.
        </li>
        <li>
          <strong>An account, if you sign in with Google.</strong> Your name, email
          address, profile picture and the account identifier Google gives us. No password
          ever reaches this site.
        </li>
        <li>
          <strong>A browser identifier, if you do not.</strong> A random id kept in your
          browser so an anonymous conversation survives a refresh. It is not linked to
          anything else.
        </li>
      </ul>
      <p>
        Recorded audio is not kept. A spoken turn is transcribed and only the resulting
        text is stored, exactly as if you had typed it.
      </p>

      <h2>What is stored when you launch an avatar</h2>
      <ul>
        <li>
          <strong>What you write about yourself.</strong> Your handle, your bio, and the
          notes on who you are, how you talk and what to avoid. Only the bio is shown to
          visitors; the rest is read by the model to answer as you.
        </li>
        <li>
          <strong>Your name and photo, in public.</strong> They come from your Google
          account and appear on your avatar&apos;s page, and in the directory once it has
          been reviewed. Your email address is never shown.
        </li>
        <li>
          <strong>When you confirmed the avatar is of you.</strong>
        </li>
      </ul>

      <h2>Who else sees it</h2>
      <ul>
        <li>
          <strong>Not the person behind the avatar.</strong> Someone who launches an
          avatar cannot read the conversations visitors have with it.
        </li>
        <li>
          <strong>The operator of {PRODUCT_NAME}.</strong> Conversations sit in a database
          that whoever runs the service can reach to keep it working.
        </li>
        <li>
          <strong>The model provider.</strong> Replies are generated by a third-party
          large language model, so your message, the recent conversation and the
          avatar&apos;s notes are sent there to produce each answer.
        </li>
        <li>
          <strong>The speech service.</strong> A spoken turn is sent to a speech service
          that transcribes it and reads the reply back.
        </li>
      </ul>
      <p>
        Nothing is sold, and nothing is used for advertising or shared with anyone beyond
        what is needed to answer you.
      </p>

      <h2>How long</h2>
      <p>
        Conversations and avatars are kept until you ask for them to be deleted. A sign-in
        lasts 30 days on a given browser, after which you sign in again.
      </p>

      <h2>Deleting it</h2>
      <p>
        Write to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> from the address
        you signed in with, and your account, your avatar and every conversation attached
        to your account will be removed. You can pause your avatar yourself at any time;
        there is no self-service delete button yet. That is a gap, not a policy.
      </p>

      <h2>Changes</h2>
      <p>
        If what this page says changes in a way that matters, you will be asked to read it
        again before your next conversation.
      </p>
    </LegalPage>
  );
}
