'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useSession } from '@/state/SessionProvider';

export function ConsentCard() {
  const { isConsentRequired, acceptCurrentTerms } = useSession();
  const [isSubmitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  if (!isConsentRequired) return null;

  const accept = async () => {
    setSubmitting(true);
    setError(null);
    try {
      await acceptCurrentTerms();
    } catch {
      setError('That did not save. Try again.');
      setSubmitting(false);
    }
  };

  return (
    <div className="consent-scrim">
      <div
        className="consent-card"
        role="dialog"
        aria-modal="true"
        aria-label="Before you start"
      >
        <h2 className="consent-title">Before you start</h2>
        <p className="consent-lede">
          Every avatar here is <strong>an AI speaking as a real person</strong>, not the
          person themselves. Three things worth knowing:
        </p>

        <ol className="consent-list">
          <li>
            <span className="consent-num">1</span>
            <span>
              What you type and say is stored against your account, and read back to the
              model on later turns so the conversation makes sense. The person behind an
              avatar cannot read your conversations with it.
            </span>
          </li>
          <li>
            <span className="consent-num">2</span>
            <span>
              Replies are generated by a third-party model provider. A spoken turn is also
              transcribed and read aloud by a speech service.
            </span>
          </li>
          <li>
            <span className="consent-num">3</span>
            <span>
              None of it is sold or used for advertising, and you can ask for all of it to
              be deleted.
            </span>
          </li>
        </ol>

        <button
          type="button"
          className="consent-accept"
          onClick={accept}
          disabled={isSubmitting}
        >
          {isSubmitting ? 'Saving…' : 'I understand'}
        </button>

        {error !== null ? <p className="consent-error">{error}</p> : null}

        <p className="consent-fineprint">
          The long version is in the <Link href="/privacy">privacy notice</Link> and the{' '}
          <Link href="/terms">terms</Link>.
        </p>
      </div>
    </div>
  );
}
